server:
  port: "8080"
mysql:
  host: "mysql"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "video_db"
redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0
jwt:
  secret: "my_super_secret_key_fanone"
minio:
  endpoint: "minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "videostorage"